Add Apple's ABI support to NativeNMethod compilation.
openjdk/aarch64-port pull request #3
Opened 2020-11-04 06:48 UTC by gonzalolarralde

This PR adds support for Apple's aarch64 C ABI, that requires stack arguments to be sized according to its data type, and considering padding properly.

Reference: https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms

/cc @AntonKozlov

2020-11-04 15:38 UTC, VladimirKempik requested changes
Hello.
I think you need to get rid of macros
>handle_padding(bytes_used, 1);
>advance_offset(bytes_used, 1);

you just put platform dependent size of type on stack in generic code

handle_padding  can be replaced with openjdk's align_up() function
 and advance_offset is simple bytes_used += size of type on stack;

size_of_type_on_stack can be made under #ifdefs in the beginning of the file

check example in our interp patch - https://github.com/openjdk/aarch64-port/commit/368f06e1cb965a68997cad0722aabcbe1068aad7


```
    _stack_offset = align_up(_stack_offset, nativeDoubleSpace);
    __ ldr(r0, src);
    __ str(r0, Address(to(), _stack_offset));
    _stack_offset += nativeDoubleSpace;
```

2020-11-17 13:03 UTC, AntonKozlov requested changes
Hi, I think there is a correctness issue that I would like to discuss

2020-11-17 13:03 UTC, AntonKozlov commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
> +#  define abi_dep_float_move(masm, src, dst, size) move_merge_and_shift(masm, src, dst, size);
`move_merge_and_shift` is unable to load to a float register (i.e. in stack->reg move), only to a general purpose one. I wonder why this was not caught by tests, but it looks like a bug

2020-11-17 13:03 UTC, AntonKozlov commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
>  int SharedRuntime::c_calling_convention(const BasicType *sig_bt,
`c_calling_convention` is used by the shared VM code, which may be confused by non-VMRegs in regs. Although I assume shared code asks convention for short signatures only, some form of assert will be useful anyway, so we'll be sure shared code won't produce unexpected result.

For example, it is possible to make a private c_calling_convention, which will be called only from the aarch64 code, which can deal with unaliged offsets on stack. And to create another "public" c_calling_convention that does not try to encode anything unusual in regs. As a side benefit, the first "private" function can encode unaligned offsets in a more straightforward way, like a a separate bitmap or array argument.

2020-11-17 13:03 UTC, AntonKozlov commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
> +  bytes_used += bytes_used % 8;
`align_up` will be a bit more straightforward

2020-11-17 13:03 UTC, AntonKozlov commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
> +  return bytes_used / 4;
Please consider using VMRegImpl::stack_slot_size (4, a fixed size slot equal `sizeof(jint)`), wordSize (8, native word size) and VMRegImpl::slots_per_word (wordSize / stack_slot_size)

2020-11-17 13:03 UTC, AntonKozlov commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
> +        __ mov(rscratch1, src.first()->as_Register());
In this case, it's better operate directly on the `src.first()->as_Register()`

2020-11-17 13:03 UTC, AntonKozlov commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
> +      __ str(rscratch1, Address(sp, reg2offset_out(dst.first())));
Can't this be replaced with just `lsr` and `strw/strh/strb`?

2020-11-17 13:03 UTC, AntonKozlov commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
>          int_args++;
It seems we have processed all necessary types above, shouldn't the default case be `ShouldNotReachHere()`?

2020-11-18 09:46 UTC, gonzalolarralde commented
Thanks for the comments @AntonKozlov, I'll try to rebuild using the latest changes on the branch that add support for MAP_JIT and get back with the feedback addressed. Due to the lack of a workaround my build + test runs were blocked, but now that those patches are public that should unblock me.

2020-11-18 09:59 UTC, gonzalolarralde commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
> +#  define abi_dep_float_move(masm, src, dst, size) move_merge_and_shift(masm, src, dst, size);
ah, I overlooked that. it seems that test cases might not be causing a displacement of float parameters, therefore never making this evaluate `true`: `(src.first() != dst.first())`. I will try to force the error and add a test if I confirm this to be the case.

2020-11-18 10:00 UTC, gonzalolarralde commented on src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp
>  int SharedRuntime::c_calling_convention(const BasicType *sig_bt,
that makes sense, will address this as you're describing. thanks!

2023-12-05 03:02 UTC, closed without merging